import components.simplereader.SimpleReader;
import components.simplereader.SimpleReader1L;
import components.simplewriter.SimpleWriter;
import components.simplewriter.SimpleWriter1L;
import components.xmltree.XMLTree;
import components.xmltree.XMLTree1;

/**
 * Program to convert an XML RSS (version 2.0) feed from a given URL into the
 * corresponding HTML output file.
 *
 * @author Selin Kirbas
 *
 */
public final class RSSReader {

    /**
     * Private constructor so this utility class cannot be instantiated.
     */
    private RSSReader() {
    }

    /**
     * Outputs the "opening" tags in the generated HTML file. These are the
     * expected elements generated by this method:
     *
     * <html>
     * <head>
     * <title>the channel tag title as the page title</title>
     * </head>
     * <body>
     * <h1>the page title inside a link to the <channel> link</h1>
     * <p>
     * the channel description
     * </p>
     * <table border="1">
     * <tr>
     * <th>Date</th>
     * <th>Source</th>
     * <th>News</th>
     * </tr>
     *
     * @param channel
     *            the channel element XMLTree
     * @param out
     *            the output stream
     * @updates out.content
     * @requires [the root of channel is a <channel> tag] and out.is_open
     * @ensures out.content = #out.content * [the HTML "opening" tags]
     */
    private static void outputHeader(XMLTree channel, SimpleWriter out) {
        assert channel != null : "Violation of: channel is not null";
        assert out != null : "Violation of: out is not null";
        assert channel.isTag() && channel.label().equals("channel") : ""
        + "Violation of: the label root of channel is a <channel> tag";
        assert out.isOpen() : "Violation of: out.is_open";

        int titleIndex = getChildElement(channel, "title");
        int descIndex = getChildElement(channel, "description");
        int linkIndex = getChildElement(channel, "link");

        out.println("<html>");
        out.println("<head>");
        out.println("<title>");

        if (!(channel.child(titleIndex).numberOfChildren() == 0)) {
            out.println(channel.child(titleIndex).child(0).label());
        } else {
            out.println("No title available");
        }
        out.println("</title>");
        out.println("</head>");
        out.println("<body>");
        if (!(channel.child(titleIndex).numberOfChildren() == 0)) {
            out.println(" <h1><a href=\""
                    + channel.child(linkIndex).child(0).label() + "\">"
                    + channel.child(titleIndex).child(0).label() + "</a></h1>");
        } else {
            out.println(" <h1><a href=\""
                    + channel.child(linkIndex).child(0).label()
                    + "\">No title available</a></h1>");
        }
        if (!(channel.child(descIndex).numberOfChildren() == 0)) {
            out.println(" <p>" + channel.child(descIndex).child(0).label()
                    + "</p>");
        } else {
            out.println(" <p>No description</p>");
        }
        out.println("<table border=\"1\">");
        out.println("<tr>");
        out.println("<th>Date</th>");
        out.println("<th>Source</th>");
        out.println("<th>News</th>");
        out.println("</tr>");
    }

    /**
     * Outputs the "closing" tags in the generated HTML file. These are the
     * expected elements generated by this method:
     *
     * </table>
     * </body>
     * </html>
     *
     * @param out
     *            the output stream
     * @updates out.contents
     * @requires out.is_open
     * @ensures out.content = #out.content * [the HTML "closing" tags]
     */
    private static void outputFooter(SimpleWriter out) {
        assert out != null : "Violation of: out is not null";
        assert out.isOpen() : "Violation of: out.is_open";

        out.println("</table>");
        out.println("</body>");
        out.println("</html>");
    }

    /**
     * Finds the first occurrence of the given tag among the children of the
     * given {@code XMLTree} and return its index; returns -1 if not found.
     *
     * @param xml
     *            the {@code XMLTree} to search
     * @param tag
     *            the tag to look for
     * @return the index of the first child of type tag of the {@code XMLTree}
     *         or -1 if not found
     * @requires [the label of the root of xml is a tag]
     * @ensures <pre>
     * getChildElement =
     *  [the index of the first child of type tag of the {@code XMLTree} or
     *   -1 if not found]
     * </pre>
     */
    private static int getChildElement(XMLTree xml, String tag) {
        assert xml != null : "Violation of: xml is not null";
        assert tag != null : "Violation of: tag is not null";
        assert xml.isTag() : "Violation of: the label root of xml is a tag";

        int i = 0, index = -1;

        while (i < xml.numberOfChildren() && index != 0) {
            if (xml.child(i).label().equals(tag)) {
                index = i;
            }
            i++;
        }
        return index;
    }

    /**
     * Processes one news item and outputs one table row. The row contains three
     * elements: the publication date, the source, and the title (or
     * description) of the item.
     *
     * @param item
     *            the news item
     * @param out
     *            the output stream
     * @updates out.content
     * @requires [the label of the root of item is an <item> tag] and
     *           out.is_open
     * @ensures <pre>
     * out.content = #out.content *
     *   [an HTML table row with publication date, source, and title of news item]
     * </pre>
     */
    private static void processItem(XMLTree item, SimpleWriter out) {
        assert item != null : "Violation of: item is not null";
        assert out != null : "Violation of: out is not null";
        assert item.isTag() && item.label().equals("item") : ""
        + "Violation of: the label root of item is an <item> tag";
        assert out.isOpen() : "Violation of: out.is_open";

        String title = "";
        String link = "";
        String srcLink = "";
        String date = "";
        String src = "";

        int pubIndex = getChildElement(item, "pubDate");
        int srcIndex = getChildElement(item, "source");
        int titleIndex = getChildElement(item, "title");
        int linkIndex = getChildElement(item, "link");

        if (pubIndex != -1) {
            if (item.child(pubIndex).numberOfChildren() != 0) {
                date = item.child(pubIndex).child(0).label();
            } else {
                date = "No date available";
            }
        }

        if (srcIndex != -1) {
            if (item.child(srcIndex).numberOfChildren() != 0) {
                src = item.child(srcIndex).child(0).label();

                srcLink = item.child(srcIndex).attributeValue("url");
            } else {
                src = "No source available";
            }
        }

        if (titleIndex != -1) {
            if (item.child(titleIndex).numberOfChildren() != 0) {
                title = item.child(titleIndex).child(0).label();
            } else {
                title = "No title available";
            }
        }

        if (linkIndex != -1) {
            if (item.child(linkIndex).numberOfChildren() != 0) {
                link = item.child(linkIndex).child(0).label();

                if (srcLink.length() != 0) {
                    out.println("<tr>");
                    out.println("<td>" + date + "</td>");
                    out.println("<td>" + "<a href=\"" + srcLink + "\">" + src
                            + "</a>" + "</td>");
                    out.println("<td>" + "<a href=\"" + link + "\">" + title
                            + "</a>" + "</td>");
                    out.println("</tr>");
                } else {
                    out.println("<tr>");
                    out.println("<td>" + date + "</td>");
                    out.println("<td>" + src + "</td>");
                    out.println("<td>" + "<a href=\"" + link + "\">" + title
                            + "</a>" + "</td>");
                    out.println("</tr>");
                }
            } else {
                if (srcLink.length() != 0) {
                    out.println("<tr>");
                    out.println("<td>" + date + "</td>");
                    out.println("<td>" + "<a href=\"" + srcLink + "\">" + src
                            + "</a>" + "</td>");
                    out.println("<td>" + title + "</td>");
                    out.println("</tr>");
                } else {
                    out.println("<tr>");
                    out.println("<td>" + date + "</td>");
                    out.println("<td>" + src + "</td>");
                    out.println("<td>" + title + "</td>");
                    out.println("</tr>");
                }

            }
        }

    }

    /**
     * Main method.
     *
     * @param args
     *            the command line arguments; unused here
     */
    public static void main(String[] args) {
        SimpleReader in = new SimpleReader1L();
        SimpleWriter out = new SimpleWriter1L();

        out.println("Please enter the URL for an RSS 2.0 feed.");
        String url = in.nextLine();
        XMLTree xml = new XMLTree1(url);

        while (!xml.label().equals("rss") && !xml.hasAttribute("version")
                && !xml.attributeValue("version").equals("2.0")) {
            out.println("Please make sure the URL is of an RSS 2.0 feed!");
            url = in.nextLine();
            xml = new XMLTree1(url);
        }

        XMLTree channel = xml.child(0);

        out.println(
                "Please enter the name of an output file inlcuding the .html extension.");
        String file = in.nextLine();
        SimpleWriter outputFile = new SimpleWriter1L(file);

        outputHeader(channel, outputFile);

        for (int i = 0; i < channel.numberOfChildren(); i++) {
            if (channel.child(i).label().equals("item")) {
                processItem(channel.child(i), outputFile);
            }
        }

        outputFooter(outputFile);

        out.print("File created. End of program.");

        outputFile.close();
        in.close();
        out.close();
    }

}
